package com.aistar.mapper;

import com.aistar.pojo.Detail;
import com.aistar.pojo.DetailExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int countByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int deleteByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int insert(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int insertSelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    List<Detail> selectByExample(DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    Detail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByExample(@Param("record") Detail record, @Param("example") DetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByPrimaryKeySelective(Detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByPrimaryKey(Detail record);
}