package com.aistar.mapper;

import com.aistar.pojo.Pro;
import com.aistar.pojo.ProExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int countByExample(ProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int deleteByExample(ProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int insert(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int insertSelective(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    List<Pro> selectByExample(ProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    Pro selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByExampleSelective(@Param("record") Pro record, @Param("example") ProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByExample(@Param("record") Pro record, @Param("example") ProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByPrimaryKeySelective(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    int updateByPrimaryKey(Pro record);
}