package com.aistar.pojo;

import java.io.Serializable;

public class Detail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.detail_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.order_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.product_num
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.status
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.detail_id
     *
     * @return the value of detail.detail_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.detail_id
     *
     * @param detailId the value for detail.detail_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.order_id
     *
     * @return the value of detail.order_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.order_id
     *
     * @param orderId the value for detail.order_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.product_id
     *
     * @return the value of detail.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.product_id
     *
     * @param productId the value for detail.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.product_num
     *
     * @return the value of detail.product_num
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.product_num
     *
     * @param productNum the value for detail.product_num
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.status
     *
     * @return the value of detail.status
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.status
     *
     * @param status the value for detail.status
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", detailId=").append(detailId);
        sb.append(", orderId=").append(orderId);
        sb.append(", productId=").append(productId);
        sb.append(", productNum=").append(productNum);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}