package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Flow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.flow_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.flow_num
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private String flowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.order_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.pay_amount
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private Float payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.pay_method
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private Integer payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow.create_time
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flow
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.flow_id
     *
     * @return the value of flow.flow_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.flow_id
     *
     * @param flowId the value for flow.flow_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.flow_num
     *
     * @return the value of flow.flow_num
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public String getFlowNum() {
        return flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.flow_num
     *
     * @param flowNum the value for flow.flow_num
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setFlowNum(String flowNum) {
        this.flowNum = flowNum == null ? null : flowNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.order_id
     *
     * @return the value of flow.order_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.order_id
     *
     * @param orderId the value for flow.order_id
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.pay_amount
     *
     * @return the value of flow.pay_amount
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public Float getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.pay_amount
     *
     * @param payAmount the value for flow.pay_amount
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setPayAmount(Float payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.pay_method
     *
     * @return the value of flow.pay_method
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public Integer getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.pay_method
     *
     * @param payMethod the value for flow.pay_method
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setPayMethod(Integer payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow.create_time
     *
     * @return the value of flow.create_time
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow.create_time
     *
     * @param createTime the value for flow.create_time
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flow
     *
     * @mbggenerated Mon Mar 16 21:44:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", flowId=").append(flowId);
        sb.append(", flowNum=").append(flowNum);
        sb.append(", orderId=").append(orderId);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", payMethod=").append(payMethod);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}