package com.aistar.pojo;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_ammount
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Float orderAmmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_create_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pay_status
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Integer orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pay_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private Date orderPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer_id
     *
     * @return the value of orders.customer_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer_id
     *
     * @param customerId the value for orders.customer_id
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_ammount
     *
     * @return the value of orders.order_ammount
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Float getOrderAmmount() {
        return orderAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_ammount
     *
     * @param orderAmmount the value for orders.order_ammount
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setOrderAmmount(Float orderAmmount) {
        this.orderAmmount = orderAmmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_create_time
     *
     * @return the value of orders.order_create_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_create_time
     *
     * @param orderCreateTime the value for orders.order_create_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pay_status
     *
     * @return the value of orders.order_pay_status
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Integer getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pay_status
     *
     * @param orderPayStatus the value for orders.order_pay_status
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setOrderPayStatus(Integer orderPayStatus) {
        this.orderPayStatus = orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pay_time
     *
     * @return the value of orders.order_pay_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public Date getOrderPayTime() {
        return orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pay_time
     *
     * @param orderPayTime the value for orders.order_pay_time
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    public void setOrderPayTime(Date orderPayTime) {
        this.orderPayTime = orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Tue Mar 17 07:38:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", customerId=").append(customerId);
        sb.append(", orderAmmount=").append(orderAmmount);
        sb.append(", orderCreateTime=").append(orderCreateTime);
        sb.append(", orderPayStatus=").append(orderPayStatus);
        sb.append(", orderPayTime=").append(orderPayTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}