package com.aistar.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class Pro implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.product_name
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.product_price
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.product_id
     *
     * @return the value of pro.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.product_id
     *
     * @param productId the value for pro.product_id
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.product_name
     *
     * @return the value of pro.product_name
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.product_name
     *
     * @param productName the value for pro.product_name
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.product_price
     *
     * @return the value of pro.product_price
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.product_price
     *
     * @param productPrice the value for pro.product_price
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbggenerated Mon Mar 16 18:29:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}